import Link from "next/link";
import { FeatherIcon } from "@/components/ui/feather-icon";

export const metadata = {
  title: "Terms of Use - Casebird",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-12">
        {/* Header */}
        <div className="mb-10">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-lg font-serif font-medium text-foreground hover:text-primary transition-colors mb-6"
          >
            <FeatherIcon className="w-5 h-5" />
            Casebird
          </Link>
          <h1 className="text-3xl font-serif font-semibold text-foreground">
            Terms of Use
          </h1>
          <p className="font-serif text-sm text-muted-foreground mt-2">
            Last updated: January 2025
          </p>
        </div>

        {/* Content */}
        <div className="font-serif text-foreground leading-relaxed space-y-8">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Casebird (&ldquo;the Service&rdquo;), you agree to be bound by
              these Terms of Use. If you do not agree to these terms, you must not use the Service.
              The Service is operated by Casebird (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Nature of the Service</h2>
            <p>
              Casebird is an AI-powered legal research tool that assists users in searching and
              analysing Hong Kong case law. The Service is designed to aid legal research and is
              intended for use by legal professionals, law students, and individuals conducting
              legal research.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              3. Not Legal Advice — No Solicitor-Client Relationship
            </h2>
            <p className="mb-3">
              <strong>
                The Service does not provide legal advice and does not create a solicitor-client
                or attorney-client relationship.
              </strong>{" "}
              All information, case summaries, analysis, and search results generated by the
              Service are provided for informational and research purposes only.
            </p>
            <p className="mb-3">
              You should not rely on the Service as a substitute for professional legal advice.
              You must always consult a qualified legal practitioner before making any legal
              decisions or taking any action based on information obtained through the Service.
            </p>
            <p>
              We expressly disclaim any responsibility for decisions made or actions taken in
              reliance on the output of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              4. AI-Generated Content — Accuracy Disclaimer
            </h2>
            <p className="mb-3">
              The Service uses artificial intelligence to generate responses, including case
              summaries, legal analysis, and search results. While we strive for accuracy,
              AI-generated content may contain:
            </p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>Errors, inaccuracies, or omissions in case citations, dates, or legal principles</li>
              <li>Incomplete or outdated information</li>
              <li>Misinterpretations of legal holdings or reasoning</li>
              <li>Fabricated or &ldquo;hallucinated&rdquo; case references that do not exist</li>
            </ul>
            <p className="mt-3">
              <strong>
                You must independently verify all case citations, quotations, legal principles,
                and factual assertions before relying on them in any professional, academic, or
                legal context.
              </strong>
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. User Responsibilities</h2>
            <p className="mb-3">When using the Service, you agree to:</p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>
                Independently verify all information obtained through the Service before relying
                on it
              </li>
              <li>
                Not upload or submit confidential, privileged, or sensitive client information
                into the Service
              </li>
              <li>
                Use the Service in compliance with all applicable laws and professional conduct
                rules
              </li>
              <li>Not use the Service for any unlawful or unauthorised purpose</li>
              <li>
                Not attempt to interfere with, disrupt, or gain unauthorised access to the Service
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. User Accounts</h2>
            <p>
              You may be required to create an account to access certain features of the Service.
              You are responsible for maintaining the confidentiality of your account credentials
              and for all activities that occur under your account. You must notify us immediately
              of any unauthorised use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Intellectual Property</h2>
            <p className="mb-3">
              The Service, including its design, features, and underlying technology, is owned by
              us and is protected by intellectual property laws. Case law and legal materials
              accessed through the Service may be subject to their own copyright and usage terms.
            </p>
            <p>
              You retain ownership of any queries or content you submit to the Service. By using
              the Service, you grant us a limited licence to process your inputs solely for the
              purpose of providing the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
            <p className="mb-3">
              To the maximum extent permitted by law, we shall not be liable for any direct,
              indirect, incidental, special, consequential, or punitive damages arising out of or
              in connection with:
            </p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>Your use of or inability to use the Service</li>
              <li>Any errors, inaccuracies, or omissions in the content generated by the Service</li>
              <li>
                Any decisions made or actions taken in reliance on information provided by the
                Service
              </li>
              <li>Any unauthorised access to or use of your account or data</li>
              <li>Any interruption or cessation of the Service</li>
            </ul>
            <p className="mt-3">
              <strong>
                The Service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without
                warranties of any kind, whether express or implied, including but not limited to
                warranties of merchantability, fitness for a particular purpose, accuracy, or
                non-infringement.
              </strong>
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Casebird, its officers, directors,
              employees, and agents from and against any claims, liabilities, damages, losses, and
              expenses arising out of or in connection with your use of the Service, your
              violation of these Terms, or your violation of any rights of a third party.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time,
              with or without cause, and with or without notice. Upon termination, your right to
              use the Service will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">11. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. We will notify you of material changes
              by posting the updated Terms on this page with a revised &ldquo;Last updated&rdquo; date. Your
              continued use of the Service after any changes constitutes acceptance of the updated
              Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the
              Hong Kong Special Administrative Region. Any disputes arising from or in connection
              with these Terms shall be subject to the exclusive jurisdiction of the courts of
              Hong Kong.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">13. Contact</h2>
            <p>
              If you have any questions about these Terms, please contact us at{" "}
              <a href="mailto:hello@casebird.com" className="text-primary hover:underline">
                hello@casebird.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
